name: CD

on:
  push:
    tags:
      - '*'

env:
  DOCKER_IMAGE: oanhnn/ngrok

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: vars
        run: |
          echo ::set-output name=version::$(echo ${GITHUB_REF##*/})

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $DOCKER_IMAGE:${{steps.vars.outputs.version}}

      - name: Show Ngrok version
        run: docker run --rm $DOCKER_IMAGE:${{steps.vars.outputs.version}} ngrok --version

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push the Docker image
        run: docker push $DOCKER_IMAGE:${{steps.vars.outputs.version}}
