name: CI

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'releases/*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: vars
        run: |
          echo ::set-output name=version::$(echo ${GITHUB_REF##*/})

      - name: Build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: oanhnn/ngrok
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
          labels: org.opencontainers.image.title=Ngrok,org.opencontainers.image.authors=oanhnn,org.opencontainers.image.licenses=MIT,org.opencontainers.image.version=${{steps.vars.outputs.version}}
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
