name: CICD

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'releases/*'
    tags:
      - '*'
  pull_request:
    branches:
      - 'master'

env:
  DOCKER_IMAGE: oanhnn/ngrok

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_SHA:10})

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag $DOCKER_IMAGE:${{steps.vars.outputs.tag}}
          docker run --rm $DOCKER_IMAGE:${{steps.vars.outputs.tag}} ngrok --version

  deploy:
    name: Deploy Docker image
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Get the version
        id: vars
        run: |
          echo ::set-output name=tag::$(echo ${GITHUB_SHA:10})
          echo ::set-output name=version::$(echo ${GITHUB_REF:10})

      - name: Push the Docker image
        run: |
          docker tag $DOCKER_IMAGE:${{steps.vars.outputs.tag}} $DOCKER_IMAGE:${{steps.vars.outputs.version}}
          docker push $DOCKER_IMAGE:${{steps.vars.outputs.version}}
